<a href="https://colab.research.google.com/github/ArtemDorofeev/Parse_elctro/blob/main/Name_selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Подключаем загрузку файла датасета с Гугл Диска
!gdown --id 19zq6J1GnjgjLoaeWc_QRlZCc1gAc0SBp
!gdown --id 1V5WcsMoB0NB6BLnnAPAxh4KQ5526ft2m

/usr/local/lib/python3.8/dist-packages/gdown/cli.py:127: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=19zq6J1GnjgjLoaeWc_QRlZCc1gAc0SBp
To: /content/prices (1).xlsx
100% 189k/189k [00:00<00:00, 75.6MB/s]
/usr/local/lib/python3.8/dist-packages/gdown/cli.py:127: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1V5WcsMoB0NB6BLnnAPAxh4KQ5526ft2m
To: /content/sin_no_art.xlsx
100% 17.4k/17.4k [00:00<00:00, 18.6MB/s]

In [ ]:
# Подключаем необходимые библиотеки 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import csv
import json

In [ ]:
# Записываем подгруженный файл excel в датафрейм, выводим информацию о нем

dp = pd.read_excel('prices (1).xlsx')
ds = pd.read_excel('sin_no_art.xlsx')

In [ ]:
dp = dp[['art', 'name']]

In [ ]:
dp

           art                                               name
0     Б0051088  МОДУЛЬ СВЕТОДИОДНЫЙ ЭРА АКСЕССУАРЫ SPB-6 С ПУЛ...
1     Б0051089  МОДУЛЬ СВЕТОДИОДНЫЙ ЭРА АКСЕССУАРЫ SPB-6 С ПУЛ...
2     Б0051090  МОДУЛЬ СВЕТОДИОДНЫЙ ЭРА АКСЕССУАРЫ SPB-6 С ПУЛ...
3     Б0051091  МОДУЛЬ СВЕТОДИОДНЫЙ ЭРА АКСЕССУАРЫ SPB-6 С ПУЛ...
4     Б0051103  ПЛАФОН ЭРА ПОДВЕСНОЙ К-Т SPB-6 - ПОДВЕСНОЙ КОМ...
...        ...                                                ...
2277  Б0052013  СВЕТИЛЬНИК ЭРА НСП 01-60-003 ПОДВЕСНОЙ ГРАНАТ ...
2278  Б0052017  СВЕТИЛЬНИК ЭРА НСП 02-100-001 БЕЗ РЕШЕТКИ ЖЕЛУ...
2279  Б0052019  СВЕТИЛЬНИК ЭРА НСП 02-100-003 С РЕШЕТКОЙ ЖЕЛУД...
2280  Б0052018  СВЕТИЛЬНИК ЭРА НСП 41-200-001 БЕЗ РЕШЕТКИ ЖЕЛУ...
2281  Б0052020  СВЕТИЛЬНИК ЭРА НСП 41-200-003 С РЕШЕТКОЙ ЖЕЛУД...

[2282 rows x 2 columns]

In [ ]:
# Делим короткое имя на части в список

ds['list'] = ds['sinonim'].apply(lambda x: x.split('-'))
ds

,id,sinonim,list
0,34747,LED-B35-7W-842-E14,"[LED, B35, 7W, 842, E14]"
1,34749,LED-B35-7W-842-E27,"[LED, B35, 7W, 842, E27]"
2,34750,LED-B35-7W-842-E27-CLEAR,"[LED, B35, 7W, 842, E27, CLEAR]"
3,34753,LED-BXS-7W-842-E14,"[LED, BXS, 7W, 842, E14]"
4,34754,LED-BXS-7W-842-E14-CLEAR,"[LED, BXS, 7W, 842, E14, CLEAR]"
...,...,...,...
356,285873,KL35,[KL35]
357,285874,KL43,[KL43]
358,285875,KL79,[KL79]
359,288634,ИНФРАКРАСНЫЙ-КЕРАМИЧЕСКИЙ-НАГРЕВАТЕЛЬ-МОЩНОСТЬ...,"[ИНФРАКРАСНЫЙ, КЕРАМИЧЕСКИЙ, НАГРЕВАТЕЛЬ, МОЩН..."
360,288635,ИНФРАКРАСНЫЙ-КЕРАМИЧЕСКИЙ-НАГРЕВАТЕЛЬ-МОЩНОСТЬ...,"[ИНФРАКРАСНЫЙ, КЕРАМИЧЕСКИЙ, НАГРЕВАТЕЛЬ, МОЩН..."

In [ ]:
print(type(ds['list'][2]))
ds['list'][2]

<class 'list'>

['LED', 'B35', '7W', '842', 'E27', 'CLEAR']

In [ ]:
shorts_list = list(dp['name'].values)
shorts_list

In [ ]:
# Генерим функцию проверки вхождения всех элементов короткого имени в длинное

def main(row):
  x = 0
  y = []
  for i in shorts_list:
    count_mod = 0
    for j in row:
      if j in i:
        count_mod += 1
      if count_mod == len(row):
        x += 1
        y.append(i)
  return [x, y]

In [ ]:
# Применяем функцию к серии list

ds['equal'] = ds['list'].apply(main)
ds

,id,sinonim,list,equal
0,34747,LED-B35-7W-842-E14,"[LED, B35, 7W, 842, E14]","[0, []]"
1,34749,LED-B35-7W-842-E27,"[LED, B35, 7W, 842, E27]","[0, []]"
2,34750,LED-B35-7W-842-E27-CLEAR,"[LED, B35, 7W, 842, E27, CLEAR]","[0, []]"
3,34753,LED-BXS-7W-842-E14,"[LED, BXS, 7W, 842, E14]","[0, []]"
4,34754,LED-BXS-7W-842-E14-CLEAR,"[LED, BXS, 7W, 842, E14, CLEAR]","[0, []]"
...,...,...,...,...
356,285873,KL35,[KL35],"[24, [KL35 A CH /1 СВЕТИЛЬНИК ЭРА ПОД ЛАМПУ GX..."
357,285874,KL43,[KL43],"[2, [KL43 SL /1 СВЕТИЛЬНИК ЭРА KL43 SL /1 ЛИТО..."
358,285875,KL79,[KL79],"[4, [KL79 WH/BK /1 СВЕТИЛЬНИК ЭРА ПОД ЛАМПУ GX..."
359,288634,ИНФРАКРАСНЫЙ-КЕРАМИЧЕСКИЙ-НАГРЕВАТЕЛЬ-МОЩНОСТЬ...,"[ИНФРАКРАСНЫЙ, КЕРАМИЧЕСКИЙ, НАГРЕВАТЕЛЬ, МОЩН...","[0, []]"
360,288635,ИНФРАКРАСНЫЙ-КЕРАМИЧЕСКИЙ-НАГРЕВАТЕЛЬ-МОЩНОСТЬ...,"[ИНФРАКРАСНЫЙ, КЕРАМИЧЕСКИЙ, НАГРЕВАТЕЛЬ, МОЩН...","[0, []]"

In [ ]:
# Выбираем строки с полным вхождением

def split_list(row):
  if row[0] > 0:
    l = row[1]
  else:
    l = []
  return l

In [ ]:
ds['small_name'] = ds['equal'].apply(split_list)

In [ ]:
df = ds[ds['small_name'].astype(bool)]

In [ ]:
df

,id,sinonim,list,equal,small_name
29,170012,LED-JC-5W-12V-827-G4,"[LED, JC, 5W, 12V, 827, G4]","[7, [ЛАМПОЧКА СВЕТОДИОДНАЯ ЭРА STD LED JC-1,5W...","[ЛАМПОЧКА СВЕТОДИОДНАЯ ЭРА STD LED JC-1,5W-12V..."
30,170013,LED-JC-5W-12V-840-G4,"[LED, JC, 5W, 12V, 840, G4]","[7, [ЛАМПОЧКА СВЕТОДИОДНАЯ ЭРА STD LED JC-1,5W...","[ЛАМПОЧКА СВЕТОДИОДНАЯ ЭРА STD LED JC-1,5W-12V..."
31,170014,LED-JC-5W-12V-COB-827-G4,"[LED, JC, 5W, 12V, COB, 827, G4]","[1, [ЛАМПОЧКА СВЕТОДИОДНАЯ ЭРА STD LED JC-1,5W...","[ЛАМПОЧКА СВЕТОДИОДНАЯ ЭРА STD LED JC-1,5W-12V..."
32,170015,LED-JC-5W-12V-COB-840-G4,"[LED, JC, 5W, 12V, COB, 840, G4]","[1, [ЛАМПОЧКА СВЕТОДИОДНАЯ ЭРА STD LED JC-1,5W...","[ЛАМПОЧКА СВЕТОДИОДНАЯ ЭРА STD LED JC-1,5W-12V..."
46,214306,ECO-LED-GX-6W-827-GX53-(10-PACK),"[ECO, LED, GX, 6W, 827, GX53, (10, PACK)]","[1, [ЛАМПОЧКА СВЕТОДИОДНАЯ ЭРА RED LINE ECO LE...",[ЛАМПОЧКА СВЕТОДИОДНАЯ ЭРА RED LINE ECO LED GX...
...,...,...,...,...,...
351,285840,LED-A60-9W-12/48V-840-E27,"[LED, A60, 9W, 12/48V, 840, E27]","[1, [ЛАМПОЧКА СВЕТОДИОДНАЯ ЭРА STD LED A60-9W-...",[ЛАМПОЧКА СВЕТОДИОДНАЯ ЭРА STD LED A60-9W-12/4...
355,285872,KL71,[KL71],"[5, [KL71 BK /1 (К) СВЕТИЛЬНИК ЭРА ПОД ЛАМПУ G...",[KL71 BK /1 (К) СВЕТИЛЬНИК ЭРА ПОД ЛАМПУ GX53 ...
356,285873,KL35,[KL35],"[24, [KL35 A CH /1 СВЕТИЛЬНИК ЭРА ПОД ЛАМПУ GX...",[KL35 A CH /1 СВЕТИЛЬНИК ЭРА ПОД ЛАМПУ GX53 ПО...
357,285874,KL43,[KL43],"[2, [KL43 SL /1 СВЕТИЛЬНИК ЭРА KL43 SL /1 ЛИТО...","[KL43 SL /1 СВЕТИЛЬНИК ЭРА KL43 SL /1 ЛИТОЙ ""А..."
358,285875,KL79,[KL79],"[4, [KL79 WH/BK /1 СВЕТИЛЬНИК ЭРА ПОД ЛАМПУ GX...",[KL79 WH/BK /1 СВЕТИЛЬНИК ЭРА ПОД ЛАМПУ GX53 К...

In [ ]:
writer = pd.ExcelWriter('cross_name1.xlsx') # write dataframe to excel 
df.to_excel(writer) # save the excel 
writer.save()

In [ ]:
print(type(df['equal'][2214]))
df['equal'][2214]

<class 'list'>

[10, ['светильник', '4012', 'подвесной', 'gх53', 'белый', 'iek']]

In [ ]:
df['equal'].value_counts()

0.0     454
1.0      91
2.0      13
3.0       8
6.0       5
4.0       5
15.0      4
5.0       2
7.0       2
10.0      2
12.0      2
9.0       2
11.0      1
Name: equal, dtype: int64

In [ ]:
df[(df['equal'] == 1.0) & (df['Артикул'].notna())]

,id,Артикул,Nom,Short,short_list,equal
1142,282865,LLE-T8-20-230-40-G13,NaN,led t8 20вт 2000лм 230в 4000к g13,"[led, t8, 20вт, 2000лм, 230в, 4000к, g13]",1.0
1143,282863,LLE-T75-12-230-40-GX53,NaN,led t75 таблетка 12вт 230в 4000к gх53,"[led, t75, таблетка, 12вт, 230в, 4000к, gх53]",1.0
1144,282862,LLE-T75-10-230-40-GX53,NaN,led t75 таблетка 10вт 230в 4000к gх53,"[led, t75, таблетка, 10вт, 230в, 4000к, gх53]",1.0
1165,282831,LLE-CORN-5-12-40-G4,NaN,led corn 5вт 12в 4000к керамика g4,"[led, corn, 5вт, 12в, 4000к, керамика, g4]",1.0
1166,282830,LLE-CORN-5-12-30-G4,NaN,led corn 5вт 12в 3000к керамика g4,"[led, corn, 5вт, 12в, 3000к, керамика, g4]",1.0
1171,282825,LLE-CORN-3-12-40-G4,NaN,led corn 3вт 12в 4000к керамика g4,"[led, corn, 3вт, 12в, 4000к, керамика, g4]",1.0
1172,282824,LLE-CORN-3-12-30-G4,NaN,led corn 3вт 12в 3000к керамика g4,"[led, corn, 3вт, 12в, 3000к, керамика, g4]",1.0
1178,282816,LLE-A60-8-48-40-E27,NaN,led a60 шар 8вт 24-48в 4000к e27,"[led, a60, шар, 8вт, 24-48в, 4000к, e27]",1.0
1179,282815,LLE-A60-8-24-40-E27,NaN,led a60 шар 8вт 12-24в 4000к e27,"[led, a60, шар, 8вт, 12-24в, 4000к, e27]",1.0
1180,282814,LLE-A60-12-48-40-E27,NaN,led a60 12вт 24-48в 4000к e27,"[led, a60, 12вт, 24-48в, 4000к, e27]",1.0
1181,282813,LLE-A60-12-24-40-E27,NaN,led a60 12вт 12-24в 4000к e27,"[led, a60, 12вт, 12-24в, 4000к, e27]",1.0
1182,282811,LLE-65-230-65-E40,NaN,led 65вт 230в 6500к e40,"[led, 65вт, 230в, 6500к, e40]",1.0
1183,282810,LLE-50-230-65-E40,NaN,led 50вт 230в 6500к e40,"[led, 50вт, 230в, 6500к, e40]",1.0
1184,282809,LLE-50-230-40-E27,NaN,led 50вт 230в 4000к e27,"[led, 50вт, 230в, 4000к, e27]",1.0
1187,282806,LLE-160-230-65-E40,NaN,led 160вт 230в 6500к e40,"[led, 160вт, 230в, 6500к, e40]",1.0
1188,282805,LLE-120-230-65-E40,NaN,led 120вт 230в 6500к e40,"[led, 120вт, 230в, 6500к, e40]",1.0
1189,282804,LLE-100-230-65-E40,NaN,led 100вт 230в 6500к e40,"[led, 100вт, 230в, 6500к, e40]",1.0
1571,223961,LDVO3-6567-36-4000-K0,NaN,дво 6567-o,"[дво, 6567-o]",1.0
1927,140487,LDSP3-1311-36-6500-K01,NaN,дсп 1311 36вт 6500к,"[дсп, 1311, 36вт, 6500к]",1.0

In [ ]:
df_c_p['mod_list'][df_c_p['Артикул'] == 'LPDO501-10-K03'].values

array([list(['сдо', '05-10', '10вт', 'ip65', '6500к', 'smd', 'сер.'])],
      dtype=object)

In [ ]:
df_p['nom_list'][df_p['Артикул'] == 'LPDO501-10-K03'].values

array([list(['прожектор', 'сдо', '05-10', 'светодиодный', 'серый', 'smd', 'ip65', 'iek'])],
      dtype=object)

In [ ]:
n = [['лампа', 'led', 'corn', 'капсула', '5вт', '230в', '3000к', 'керамика', 'e14', 'iek'], 
     ['светильник', 'светодиодный', 'дво', '6561-p', '36вт', '4000к', '595х595х20', 'призма', 'iek'], 
     ['светильник', 'светодиодный', 'дпо', '3030д', '12вт', '4500k', 'ip54', 'круг', 'белый', 'пластик', 'с', 'дд', 'iek']]
m = ['дво', '6561-p', '36вт', '4000к', '595x595x20', 'призма']

In [ ]:
x = 0
for i in n:
  count_mod = 0
  for j in m:
    if j in i:
      count_mod += 1
  if count_mod == len(m):
    x += 1       

print(x)

0